### ISSUE TITLE
Manual creation of SA Services

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Common-Services#2]
AS a Chatbot trainer
I WANT TO write needed DSL files
SO THAT end users could consume SA's Services via Bürokratt

### Acceptance Criteria

- [x] buerokratt/Service-Module#61
- [ ] buerokratt/Service-Module#62
- [ ] buerokratt/Service-Module#63
- [ ] buerokratt/Service-Module#64
- [ ] buerokratt/Service-Module#65
