### ISSUE TITLE
Business register (Äriregister) service

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Common-Services#31]
AS A Service manager
I WANT TO have Business register service available in Bürokratt
SO THAT I can get information from Business register about businesses

### Acceptance Criteria

- [x] End User is able to get information about businesses contact information. When End User asks companies contact information wether it's only one information field (for example phone), Bürokratt will provide all information about companies contact details (except fax) - https://avaandmed.ariregister.rik.ee/et/ariregistri-avaandmete-api/ettevotja-detailandmete-paring
- [x] When End User asks general information about business then following information will be provided: Registrikood, Õiguslik vorm, Staatus, Kapital ja Registreeritud. When asked separately, all information will be provided. - https://avaandmed.ariregister.rik.ee/et/ariregistri-avaandmete-api/ettevotja-lihtandmete-paring-staatuse-paring
- [x]  When End User asks about beneficial owners (Tegelik kasusaaja) of the business then the name will be provided - https://avaandmed.ariregister.rik.ee/et/ariregistri-avaandmete-api/tegelike-kasusaajate-andmete-paring

> [!NOTE]
> Added 01.10.2024

- [ ] End Client gets responses when asking about Business Register-related Services without knowing exactly how to trigger the Service

Information about API: https://avaandmed.ariregister.rik.ee/et/ariregistri-avaandmete-api/api-teenuste-tutvustus

> [!NOTE]
> Added 25.09.2024

- [x] #68

> [!NOTE]
> Added 26.09.2024

- [x] #67
- [x] #69

**Comment by RayDNoper** [comment]
Endpoints in XTR v3: 

* /ar/detailandmed_v2 
  - reg_code
  - username
  - password
  
* /ar/lihtandmed_v3
  - reg_code
  - username
  - password

* /ar/ettevottegaSeotudIsikud_v1
  - reg_code

XTR v3 can currently be accessed in dev environment via local network http://192.168.42.65:9020

**Comment by ValterAro** [comment]
There needs to be some modifications done to the current pull request (https://github.com/buerokratt/Common-Services/pull/55) in order to get it to work in the service flow. The main issue is with the hbs files. The currently expected format for the hbs files looks like this: https://github.com/buerokratt/Buerokratt-DSL/blob/test-tmp-6/DataMapper/v1/Common-Services/hbs/get_employees_with_code.handlebars  
```
{
    "employees": [
    {{#each hits}}
            {
              "text": "{{ _source.workers }} inimest töötab firmas {{ _source.name }}",
              "result": "{{ _source.name }}"
            }{{#unless @last}},{{/unless}}
    {{/each}}
    ]
}
```
and in the proposed implementation the hbs files look like this: https://github.com/buerokratt/Common-Services/pull/55/files#diff-e159e3e428f31fd772b1f2b960e28296fc4256a19ed8124c3cc370abe23736c7 
```
{
    "ariregistri_kood": {{ keha.ariregistri_kood }},
    "nimi": {{ keha.nimi }},
    "sidevahendid": [
    {{#each keha.yldandmed.sidevahendid.item }}
        {
            "liik": {{ liik }},
            "sisu": {{ sisu }}
        }
    {{/each}}
    ]
}
```

**Comment by joonasroosalung** [comment]
Updated here https://github.com/buerokratt/Common-Services/pull/58

**Comment by ValterAro** [comment]
I will make a pull request for the chatbot repo dev branch once it has been updated to the latest version. Also The common-services repo PR is this https://github.com/buerokratt/Common-Services/pull/57 .

**Comment by ValterAro** [comment]
The changes to chatbot repository are here https://github.com/buerokratt/Buerokratt-Chatbot/pull/834

**Comment by turnerrainer** [comment]
Tested, but output needs further processing.

**Comment by turnerrainer** [comment]
Blocked as the following AC is not fulfilled:

- [ ] End Client gets responses when asking about Business Register-related Services without knowing exactly how to trigger the Service

**Comment by turnerrainer** [comment]
> Blocked as the following AC is not fulfilled:
> 
> * [ ]  End Client gets responses when asking about Business Register-related Services without knowing exactly how to trigger the Service

LLM detects the services correctly
