### ISSUE TITLE
Data import pipeline

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Common-Services#33]
AS AN Architect
I WANT TO have a data import pipeline
SO THAT it could be used based on the same principles for different use cases

### Acceptance Criteria

- [ ] `CSV` files are used as input
- [ ] Text files as input are considered as persistent storage
- [ ] OpenSearch is not considered as a persistent storage but is used to perform fast search queries
- [ ] Different types of documents use their respective OpenSearch index
- [ ] ~Initiatilization of data import is triggered by calling respective REST endpoint~
- [ ] Initiatilization of data import is triggered as a CronManager work
- [ ] Unprocessed files are stored locally in `/{service}/unprocessed` folder
- [ ] Processed files are stored locally in `/{service}/processed` folder
- [ ] Relational database to store state is out of scope of this issue
- [ ] Every service has its own OpenSearch field mapping

#### DSL

- [ ] REST service to import contents of a `CSV` file to OpenSearch
- [ ] Cronjob to initialize importing the contents of a `CSV` file to OpenSearch

#### Scope

> [!NOTE]
> Different datasets will be imported to validate that the pipeline in generic

- [x] #34
- [ ] #35
- [ ] #36
