### ISSUE TITLE
Common services based on Tax and Customs Board's open data

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Common-Services#37]
AS A Product Owner
I WANT TO have common services based on Tax and Customs Board's open data
SO THAT I could provide tax-related common services based on data provided by a verified third-party

### Acceptance Criteria

- [ ] All services as separate `REST` endpoints
- [ ] All services provide relevant information about a specific company
- [ ] All services provide summarized relevant information
- [ ] Queries based on fixed time frame (quarter)
- [ ] Service queries can be grouped by EMTAK
- [ ] Service queries can be grouped by county

#### Scope

- [ ] #38
- [ ] #39
- [ ] #40
- [ ] #41
- [ ] #42

#### Data schema

> [!NOTE]
> All services as part of this epic will be based on the following data schema

```json
{
  "mappings": {
    "properties": {
      "registry_code": {
        "type": "text"
      },
      "name": {
        "type": "string"
      },
      "type": {
        "type": "text"
      },
      "vat_register": {
        "type": "text"
      },
      "emtak_field_of_activity": {
        "type": "text"
      },
      "county": {
        "type": "text"
      },
      "national_taxes": {
        "type": "text"
      },
      "labor_taxes_and_payments": {
        "type": "text"
      },
      "turnover": {
        "type": "text"
      },
      "workers": {
        "type": "text"
      }
    }
  }
}
```

**Comment by 1AhmedYasser** [comment]
Added an ingest [companies pipeline](https://github.com/buerokratt/Common-Services/blob/dev/DSL/OpenSearch/pipelines/companies-pipeline.json) to make sure to filter the data before adding it to open search. 

It Currently does the following:
1. Makes sure that any empty employee field is replaced with 0
2. Makes sure that employee are converted to integer
3. Makes sure that any empty national taxes field is replaced with 0
4. Makes sure that national taxes field is formatted correctly so that for example `100,2` is formated to `100.2`
5. Makes sure that national taxes field is converted to double 
6. Makes sure that any empty paid workforce taxes field is replaced with 0
7. Makes sure that paid workforce taxes field is formatted correctly so that for example `233,62` is formated to `233.62`
8. Makes sure that paid workforce taxes field is converted to double 
9.  Makes sure that any empty revenue field is replaced with 0
10. Make sure that revenue field is formatted correctly so that for example `300,789` is formated to `300.789`
11. Make sure that revenue field is converted to double

**Comment by RiinaLi** [comment]
Tax and Custom's Board service
[#89](https://github.com/buerokratt/Common-Services/issues/89)
