### ISSUE TITLE
Common Service for national holidays

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Common-Services#59]
AS AN End Client
I WANT TO get information about Estonian national holidays
SO THAT I could use it for whatever purpose I had

### Acceptance Criteria

- [x] Responses are based on [up-to-date information about national holidays](https://github.com/buerokratt/Common-Services/issues/60)
- [x] Use Bürokratt Chat Widget to specify my requests in writing and get answers for them
- [x] #61
- [x] #63

#### Scope

- [x] All functionalities of #60

**Comment by turnerrainer** [comment]
Blocked until `/chat/message-to-bot` is refactored and Rasa trained properly

**Comment by turnerrainer** [comment]
Blocked by
https://github.com/buerokratt/Common-Services/issues/61
https://github.com/buerokratt/Common-Services/issues/63

**Comment by jaX10bt** [comment]
Works as intended
