### ISSUE TITLE
Weather Service

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Common-Services#71]
AS A Product Owner
I WANT TO have Weather Service available for End Clients
SO THAT they could get answers to their weather-related questions

### Acceptance Criteria

- [x] Bürokratt understands weather-related questions in natural language
- [x] The End Client can specify the region to get weather information about
- [ ] The End Client can specify the time period to get weather information about

#### DSL

- [ ] #72
- [x] #73

**Comment by ffrose** [comment]
PR: https://github.com/buerokratt/Training-Module/pull/675

**Comment by ffrose** [comment]
Blocked until region-based search API starts working again. As of right now, this is hard coded to answer Tallinn weather.

**Comment by turnerrainer** [comment]
> Blocked until region-based search API starts working again. As of right now, this is hard coded to answer Tallinn weather.

Resolved
