### ISSUE TITLE
REST service to fetch weather information about a specific region

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Common-Services#73]
> [!NOTE]
> This is a sub-task of #71 

AS AN Architect
I WANT TO have a REST service to fetch weather information about a specific region
SO THAT any kind of applicable services could be built on top of it

### Acceptance Criteria

- [x] Only `POST` requests accepted
- [x] Endpoint `/services/weather/{country_code}`
- [x] Use `EE` (Estonia) as a default `{country_code}`
- [x] Accept `{country_code}` as input
- [x] Require `{region}` as input
- [x] ~Require `{date}` as input~
- [x] ~Accept `{time}` as an optional input~
- [x] `README.md` to cover the usage of the service

#### Sample End Client requests

> [!NOTE]
> Examples here in English, but in applicable language based on service `{country_code}`

- [x] _"What's the weather like in Tallinn?"_
- [x] _"What's the weather like in Pärnu?"_

#### Scope

- [x] #74

**Comment by matKlju** [comment]
Current issue:
API: https://publicapi.envir.ee/v1/combinedWeatherData 
Api currently not compatible with header: Accept: "application/json"

*yml has default values hardcoded and always defaults to "tallinn"

**Comment by jaX10bt** [comment]
Currently weather service only responds with weather in Tallinn

**Comment by matKlju** [comment]
> Currently weather service only responds with weather in Tallinn

Fixed. Weather service reacts to all Estonian cities.

**Comment by jaX10bt** [comment]
Works as intended
